"""Visual output generators (images, infographics, videos)."""

import asyncio
import base64
import io
import logging
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

from PIL import Image, ImageDraw, ImageFont

from app.core.models import Cluster, ContentItem
from app.output.generators.base import BaseOutputGenerator
from app.output.models import (
    GeneratedOutput,
    OutputFormat,
    OutputMetadata,
    OutputPreferences,
    OutputRequest,
    VisualizationType,
)


class InfographicGenerator(BaseOutputGenerator):
    """Generate infographic images from content."""

    def __init__(self, preferences: OutputPreferences):
        """Initialize infographic generator."""
        super().__init__(preferences)
        self.width = 1200
        self.height = 1600
        self.background_color = (255, 255, 255)
        self.text_color = (33, 33, 33)
        self.accent_color = (66, 133, 244)

    async def generate(
        self,
        request: OutputRequest,
        clusters: List[Cluster],
        items: List[ContentItem],
        **kwargs,
    ) -> GeneratedOutput:
        """Generate infographic image."""
        start_time = time.time()

        # Create image
        img = Image.new("RGB", (self.width, self.height), self.background_color)
        draw = ImageDraw.Draw(img)

        # Load fonts (fallback to default if custom fonts not available)
        try:
            title_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 48)
            heading_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32)
            body_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 24)
        except (OSError, IOError) as e:
            logger.warning(f"Failed to load custom fonts, using default: {e}")
            title_font = ImageFont.load_default()
            heading_font = ImageFont.load_default()
            body_font = ImageFont.load_default()

        y_offset = 50

        # Draw title
        title = f"Intelligence Digest"
        draw.text((50, y_offset), title, fill=self.text_color, font=title_font)
        y_offset += 100

        # Draw date
        from datetime import datetime
        date_str = datetime.utcnow().strftime("%B %d, %Y")
        draw.text((50, y_offset), date_str, fill=self.accent_color, font=body_font)
        y_offset += 80

        # Draw clusters
        for i, cluster in enumerate(clusters[:5], 1):  # Max 5 clusters
            # Draw cluster number badge
            badge_x = 50
            badge_y = y_offset
            badge_radius = 20
            draw.ellipse(
                [badge_x, badge_y, badge_x + badge_radius * 2, badge_y + badge_radius * 2],
                fill=self.accent_color,
            )
            draw.text(
                (badge_x + badge_radius - 5, badge_y + 5),
                str(i),
                fill=(255, 255, 255),
                font=body_font,
            )

            # Draw cluster topic
            topic_x = badge_x + badge_radius * 2 + 20
            draw.text((topic_x, y_offset), cluster.topic[:50], fill=self.text_color, font=heading_font)
            y_offset += 50

            # Draw cluster summary (truncated)
            summary = cluster.summary[:150] + "..." if len(cluster.summary) > 150 else cluster.summary
            # Word wrap
            words = summary.split()
            lines = []
            current_line = []
            for word in words:
                current_line.append(word)
                test_line = " ".join(current_line)
                bbox = draw.textbbox((0, 0), test_line, font=body_font)
                if bbox[2] > self.width - 100:
                    current_line.pop()
                    lines.append(" ".join(current_line))
                    current_line = [word]
            if current_line:
                lines.append(" ".join(current_line))

            for line in lines[:3]:  # Max 3 lines
                draw.text((topic_x, y_offset), line, fill=self.text_color, font=body_font)
                y_offset += 35

            y_offset += 40

            if y_offset > self.height - 200:
                break

        # Draw footer
        footer_y = self.height - 100
        draw.line([(50, footer_y), (self.width - 50, footer_y)], fill=self.accent_color, width=2)
        footer_text = f"Generated by Social Media Radar • {len(items)} sources analyzed"
        draw.text((50, footer_y + 20), footer_text, fill=self.text_color, font=body_font)

        # Save to bytes
        img_bytes = io.BytesIO()
        img.save(img_bytes, format="PNG", optimize=True)
        img_bytes.seek(0)

        generation_time_ms = int((time.time() - start_time) * 1000)

        metadata = OutputMetadata(
            format=OutputFormat.IMAGE,
            generation_time_ms=generation_time_ms,
            file_size_bytes=len(img_bytes.getvalue()),
        )

        # Encode image as base64 for storage
        img_base64 = base64.b64encode(img_bytes.getvalue()).decode()

        output = GeneratedOutput(
            user_id=request.user_id,
            digest_id=request.digest_id,
            preferences_id=request.preferences_id or self.preferences.id,
            format=OutputFormat.IMAGE,
            content=img_base64,  # Base64 encoded image
            media_files={"infographic.png": img_bytes.getvalue()},
            metadata=metadata,
            title="Daily Intelligence Infographic",
        )

        metadata.quality_score = self._calculate_quality_score(output)

        return output

    async def validate_output(self, output: GeneratedOutput) -> bool:
        """Validate infographic output."""
        # Check if image was generated
        if not output.content:
            return False

        # Check file size (should be reasonable)
        if output.metadata.file_size_bytes and output.metadata.file_size_bytes > 10 * 1024 * 1024:  # 10MB
            return False

        return True


class VideoGenerator(BaseOutputGenerator):
    """Generate AI video summaries (placeholder for future implementation)."""

    def __init__(self, preferences: OutputPreferences):
        """Initialize video generator."""
        super().__init__(preferences)

    async def generate(
        self,
        request: OutputRequest,
        clusters: List[Cluster],
        items: List[ContentItem],
        **kwargs,
    ) -> GeneratedOutput:
        """Generate video summary.

        This is a placeholder. In production, this would:
        1. Generate script from clusters
        2. Use TTS to create voiceover
        3. Generate visuals using AI (Stable Diffusion, etc.)
        4. Combine with video editing tools (FFmpeg)
        5. Add background music and transitions
        """
        start_time = time.time()

        # For now, return a placeholder
        script = self._generate_script(clusters, items)

        generation_time_ms = int((time.time() - start_time) * 1000)

        metadata = OutputMetadata(
            format=OutputFormat.VIDEO,
            generation_time_ms=generation_time_ms,
            word_count=len(script.split()),
        )

        output = GeneratedOutput(
            user_id=request.user_id,
            digest_id=request.digest_id,
            preferences_id=request.preferences_id or self.preferences.id,
            format=OutputFormat.VIDEO,
            content=script,  # Video script for now
            metadata=metadata,
            title="Daily Intelligence Video",
            summary="AI-generated video summary (script only - video generation coming soon)",
        )

        return output

    def _generate_script(self, clusters: List[Cluster], items: List[ContentItem]) -> str:
        """Generate video script."""
        script_parts = []

        script_parts.append("# Video Script: Daily Intelligence Digest\n\n")
        script_parts.append("## Opening\n")
        script_parts.append(
            f"Welcome to your daily intelligence digest. Today we're covering {len(clusters)} major topics.\n\n"
        )

        for i, cluster in enumerate(clusters[:5], 1):
            script_parts.append(f"## Segment {i}: {cluster.topic}\n")
            script_parts.append(f"{cluster.summary}\n\n")
            script_parts.append(f"[Visual: Show key statistics and sources]\n\n")

        script_parts.append("## Closing\n")
        script_parts.append(
            "That's your intelligence digest for today. Stay informed, stay ahead.\n"
        )

        return "".join(script_parts)

    async def validate_output(self, output: GeneratedOutput) -> bool:
        """Validate video output."""
        return len(output.content) > 100  # Basic validation

